# Generated by Django 5.1.1 on 2024-10-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_remove_variacion_modelo_remove_variacion_size'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='almacen.variacion'),
        ),
    ]
