# Generated by Django 5.1.1 on 2024-10-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_pago_id_alter_pedido_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nota_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
