# Generated by Django 5.1.1 on 2024-10-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cuentas', '0004_cuenta_groups_cuenta_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuenta',
            new_name='Usuario',
        ),
    ]
