# Generated by Django 5.1.1 on 2024-10-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_rename_usuario_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
