# Generated by Django 5.1.1 on 2024-10-10 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_cuenta_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='phone_number',
            new_name='telefono',
        ),
    ]
