# Generated by Django 5.1.1 on 2024-10-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_rename_phone_number_cuenta_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
