# Generated by Django 5.1.1 on 2024-10-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_cuenta_genero_alter_cuenta_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='ciudad',
        ),
    ]
