# Generated by Django 5.1.1 on 2024-10-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_variacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacion',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='variacion',
            name='size',
        ),
    ]
